FROM centos:7

MAINTAINER Eric Mugerwa <ericmdev@gmail.com>

LABEL version="1.0"
LABEL description="Perl, Vim, Git"

RUN yum update -y
RUN yum install perl -y
RUN yum install vim -y
RUN yum install git -y
RUN yum clean all